### ISSUE TITLE
Optimized Ionic-Angular CSS Bundle is not work for me

### ISSUE THREAD

**Issue by JohnNiuNiu** [shprink/ionic-twitter-pwa#3]
hi,
I liked this article 'Optimized Ionic-Angular CSS Bundle for PWA'
https://julienrenaux.fr/2017/07/20/optimized-ionic-angular-css-bundle-for-pwas/

Read it caref，i do not hesitate to try it ，but it is not work for me;  main.css is not reduced as before

I don't know why，Thank you in advance

my ionic info:
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3 browser 4.1.0 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.3

System:

    Node       : v6.10.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002
    ios-deploy : 1.9.1
    ios-sim    : 5.0.13
    npm        : 3.10.10

**Comment by shprink** [comment]
ok, I will need a little bit more info about what's not working. Closing this issue because it has nothing to do with this repo.
Do not hesitate to continue commenting here.

**Comment by JohnNiuNiu** [comment]
First of all thank you very much
it work now.it is my fault ,my mistake.
