### ISSUE TITLE
Links don't work (page-tweet-details duplicated)

### ISSUE THREAD

**Issue by jrmlt** [shprink/ionic-twitter-pwa#4]
Hello,

Every time I want to open a link, a new `page-tweet-details` is pushed to the stack.

For example in the screenshot below:
![image](https://user-images.githubusercontent.com/29088905/28957214-3c95fd64-78f1-11e7-8ede-ca48837585ff.png)

The link is not opened and a new page is added to the nav stack:
![image](https://user-images.githubusercontent.com/29088905/28957266-844b4f42-78f1-11e7-974c-3634bda6385d.png)

Hope it helps. Thanks for the great app.

**Comment by shprink** [comment]
thanks for sharing. Building, should be online in 5 min
