### ISSUE TITLE
How to embed a Tweet ?

### ISSUE THREAD

**Issue by valentin-harrang** [shprink/ionic-twitter-pwa#6]
Hi,

It's a very good job! But I have a question to go even further in the process. 

How could we integrate a tweet (equivalent of the code obtained when we click on "Embed the tweet" in Twitter) in an Ionic app?

**Comment by shprink** [comment]
Hello,

thanks but you better ask on the Ionic Slack instead of here. 

https://ionicworldwide.herokuapp.com/
